spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:./db/voting
    username: sa
    password:
  sql:
    init:
      mode: always
      encoding: UTF-8
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
logging:
  level:
    root: WARN
    com.vorsa.restaurantvoting: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG